package foundation

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"strconv"
	"strings"
	
	"github.com/danielmiessler/fabric/plugins/ai"
	"github.com/danielmiessler/fabric/plugins/db/fsdb"
	"github.com/danielmiessler/fabric/core"
)

// FabricConfig manages interaction with Fabric's configuration
type FabricConfig struct {
	paths      *FabricPaths
	fabricDB   *fsdb.Db
	registry   *core.PluginRegistry
	
	// Cached configuration values
	configValues map[string]string
}

// NewFabricConfig creates a new configuration manager
func NewFabricConfig(paths *FabricPaths) *FabricConfig {
	return &FabricConfig{
		paths:        paths,
		configValues: make(map[string]string),
	}
}

// Initialize sets up the Fabric database and registry
func (fc *FabricConfig) Initialize() error {
	log.Println("Initializing Fabric configuration...")
	
	// Initialize Fabric's database
	fc.fabricDB = fsdb.NewDb(fc.paths.ConfigDir)
	if err := fc.fabricDB.Configure(); err != nil {
		log.Printf("Warning: Fabric DB configuration failed: %v", err)
		// Continue anyway, but functionality may be limited
	}
	
	// Initialize Fabric's core PluginRegistry
	registry, err := core.NewPluginRegistry(fc.fabricDB)
	if err != nil {
		return fmt.Errorf("failed to initialize Fabric Plugin Registry: %w", err)
	}
	
	if err := registry.Configure(); err != nil {
		log.Printf("Warning: Fabric Plugin Registry configuration failed: %v", err)
		// Continue anyway, but AI models might not be available
	}
	
	fc.registry = registry
	
	// Load configuration from .env file
	if err := fc.loadEnvConfig(); err != nil {
		log.Printf("Warning: Failed to load .env configuration: %v", err)
		// Continue with defaults
	}
	
	return nil
}

// loadEnvConfig loads configuration from .env file
func (fc *FabricConfig) loadEnvConfig() error {
	if _, err := os.Stat(fc.paths.EnvFile); os.IsNotExist(err) {
		return fmt.Errorf(".env file not found at %s", fc.paths.EnvFile)
	}
	
	file, err := os.Open(fc.paths.EnvFile)
	if err != nil {
		return err
	}
	defer file.Close()
	
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		line = strings.TrimSpace(line)
		
		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		
		// Parse key=value pairs
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue // Invalid format, skip
		}
		
		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])
		
		// Remove quotes if present
		value = strings.Trim(value, "\"'")
		
		fc.configValues[key] = value
	}
	
	if err := scanner.Err(); err != nil {
		return err
	}
	
	log.Printf("Loaded %d configuration values from .env", len(fc.configValues))
	return nil
}

// SaveEnvConfig saves current configuration to .env file
func (fc *FabricConfig) SaveEnvConfig() error {
	// Create directory if it doesn't exist
	if err := os.MkdirAll(fc.paths.ConfigDir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}
	
	// Create or truncate the .env file
	file, err := os.Create(fc.paths.EnvFile)
	if err != nil {
		return fmt.Errorf("failed to create .env file: %w", err)
	}
	defer file.Close()
	
	// Write header
	file.WriteString("# Fabric Configuration\n# Generated by Fabric GUI\n\n")
	
	// Write key-value pairs
	for key, value := range fc.configValues {
		file.WriteString(fmt.Sprintf("%s=%s\n", key, value))
	}
	
	log.Println("Saved configuration to", fc.paths.EnvFile)
	return nil
}

// GetConfig retrieves a configuration value
func (fc *FabricConfig) GetConfig(key, defaultValue string) string {
	if value, ok := fc.configValues[key]; ok {
		return value
	}
	
	// Check defaults from registry if available
	if fc.registry != nil && fc.registry.Defaults != nil {
		switch key {
		case "DEFAULT_MODEL":
			return fc.registry.Defaults.Model.Value
		case "DEFAULT_VENDOR":
			return fc.registry.Defaults.Vendor.Value
		}
	}
	
	return defaultValue
}

// SetConfig sets a configuration value
func (fc *FabricConfig) SetConfig(key, value string) {
	fc.configValues[key] = value
}

// GetFloat64Config retrieves a float64 configuration value
func (fc *FabricConfig) GetFloat64Config(key string, defaultValue float64) float64 {
	strValue := fc.GetConfig(key, fmt.Sprintf("%f", defaultValue))
	value, err := strconv.ParseFloat(strValue, 64)
	if err != nil {
		return defaultValue
	}
	return value
}

// SetFloat64Config sets a float64 configuration value
func (fc *FabricConfig) SetFloat64Config(key string, value float64) {
	fc.configValues[key] = fmt.Sprintf("%f", value)
}

// GetIntConfig retrieves an integer configuration value
func (fc *FabricConfig) GetIntConfig(key string, defaultValue int) int {
	strValue := fc.GetConfig(key, fmt.Sprintf("%d", defaultValue))
	value, err := strconv.Atoi(strValue)
	if err != nil {
		return defaultValue
	}
	return value
}

// SetIntConfig sets an integer configuration value
func (fc *FabricConfig) SetIntConfig(key string, value int) {
	fc.configValues[key] = fmt.Sprintf("%d", value)
}

// LoadVendors loads just the available AI vendors (not their models)
func (fc *FabricConfig) LoadVendors() ([]string, error) {
	if fc.registry == nil {
		return nil, fmt.Errorf("Fabric registry not initialized")
	}
	
	// Get the VendorsManager from the registry
	vendorManager := fc.registry.VendorManager
	
	// Extract vendors only (don't load models yet)
	vendors := make([]string, 0, len(vendorManager.Vendors))
	
	for _, vendor := range vendorManager.Vendors {
		vendorName := vendor.GetName()
		vendors = append(vendors, vendorName)
	}
	
	return vendors, nil
}

// LoadModelsForVendor loads models for a specific vendor only
func (fc *FabricConfig) LoadModelsForVendor(vendorName string) ([]string, error) {
	if fc.registry == nil {
		return nil, fmt.Errorf("Fabric registry not initialized")
	}
	
	// Get the VendorsManager from the registry
	vendorManager := fc.registry.VendorManager
	
	// Find the vendor
	var targetVendor ai.Vendor
	for _, vendor := range vendorManager.Vendors {
		if vendor.GetName() == vendorName {
			targetVendor = vendor
			break
		}
	}
	
	if targetVendor == nil {
		return nil, fmt.Errorf("vendor %s not found", vendorName)
	}
	
	// Load models for this vendor only
	models, err := targetVendor.ListModels()
	if err != nil {
		return nil, fmt.Errorf("failed to list models for vendor %s: %w", vendorName, err)
	}
	
	return models, nil
}

// LoadModelsAndVendors loads the available AI models and vendors (for compatibility)
func (fc *FabricConfig) LoadModelsAndVendors() ([]string, map[string][]string, error) {
	// First load vendors
	vendors, err := fc.LoadVendors()
	if err != nil {
		return nil, nil, err
	}
	
	// Initialize models map
	modelsByVendor := make(map[string][]string)
	
	// Load models for each vendor
	for _, vendorName := range vendors {
		models, err := fc.LoadModelsForVendor(vendorName)
		if err != nil {
			log.Printf("Warning: Could not list models for vendor %s: %v", vendorName, err)
			continue
		}
		modelsByVendor[vendorName] = models
	}
	
	return vendors, modelsByVendor, nil
}

// LoadPatterns loads all patterns from Fabric's database
func (fc *FabricConfig) LoadPatterns() ([]Pattern, error) {
	if fc.fabricDB == nil {
		return nil, fmt.Errorf("Fabric database not initialized")
	}
	
	// Skip DB loading and use filesystem directly since ListAll isn't available
	log.Println("Loading patterns directly from filesystem")
	return fc.loadPatternsFromFilesystem()
}

// loadPatternsFromFilesystem loads patterns directly from the filesystem
func (fc *FabricConfig) loadPatternsFromFilesystem() ([]Pattern, error) {
	patternLoader := NewPatternLoader(fc.paths.PatternsDir, fc.paths.DescriptionsPath)
	patterns, err := patternLoader.LoadAllPatterns()
	if err != nil {
		return nil, fmt.Errorf("failed to load patterns from filesystem: %w", err)
	}
	
	log.Printf("Loaded %d patterns from filesystem", len(patterns))
	return patterns, nil
}

// GetDefaultAppState populates an AppState with config values
func (fc *FabricConfig) GetDefaultAppState() *AppState {
	state := NewAppState()
	
	// Load model config
	state.CurrentModelID = fc.GetConfig("DEFAULT_MODEL", "gpt-4o") // Default to a reasonable choice
	state.CurrentVendorID = fc.GetConfig("DEFAULT_VENDOR", "openai") // Default to a reasonable choice
	state.CurrentModelName = state.CurrentModelID // Will be updated later with friendly name if available
	
	// Load model parameters
	state.Temperature = fc.GetFloat64Config("TEMPERATURE", 0.7)
	state.TopP = fc.GetFloat64Config("TOP_P", 0.9)
	state.PresencePenalty = fc.GetFloat64Config("PRESENCE_PENALTY", 0.0)
	state.FrequencyPenalty = fc.GetFloat64Config("FREQUENCY_PENALTY", 0.0)
	state.Seed = fc.GetIntConfig("SEED", 0)
	state.ContextLength = fc.GetIntConfig("CONTEXT_LENGTH", 4096)
	state.Strategy = fc.GetConfig("STRATEGY", "standard")
	
	return state
}

// SaveAppStateToConfig saves AppState values to config
func (fc *FabricConfig) SaveAppStateToConfig(state *AppState) {
	// Save model config
	fc.SetConfig("DEFAULT_MODEL", state.CurrentModelID)
	fc.SetConfig("DEFAULT_VENDOR", state.CurrentVendorID)
	
	// Save model parameters
	fc.SetFloat64Config("TEMPERATURE", state.Temperature)
	fc.SetFloat64Config("TOP_P", state.TopP)
	fc.SetFloat64Config("PRESENCE_PENALTY", state.PresencePenalty)
	fc.SetFloat64Config("FREQUENCY_PENALTY", state.FrequencyPenalty)
	fc.SetIntConfig("SEED", state.Seed)
	fc.SetIntConfig("CONTEXT_LENGTH", state.ContextLength)
	fc.SetConfig("STRATEGY", state.Strategy)
	
	// Save to file
	if err := fc.SaveEnvConfig(); err != nil {
		log.Printf("Warning: Failed to save configuration: %v", err)
	}
}